export const FETCH_BEGIN = 'FETCH_BEGIN'
export const FETCH_END_SUCCESS = 'FETCH_END_SUCCESS'
export const FETCH_END_FAILURE = 'FETCH_END_FAILURE'

export const HOME_MOVIES_LOAD = 'HOME_MOVIES_LOAD'


export const MOVIES_SEARCH = 'MOVIES_SEARCH'
